### ISSUE TITLE
Cached errors are obfuscating source of problem

### ISSUE THREAD

**Issue by remy** [maticzav/graphql-shield#263]
# Bug report

* [x] I have checked other issues to make sure this is not a duplicate (note that a similar-ish bug exists, but it doesn't describe the core of the problem).

## Describe the bug

I've had multiple bugs in my rules, a typical bug would be when I try to access `context.user.id` when there's no `user` object on the `context` (because the user wasn't signed in). What happens is that graph-shield triggers the `fallbackError` response.

Since the `fallbackError` object is created inside the `normalizeOptions` function, the stracktrace detailing where the error only mentions this generation function:

```
Error: Unknown error (in shield)
    at normalizeOptions (app/node_modules/graphql-shield/dist/shield.js:18:33)
    at shield (app/node_modules/graphql-shield/dist/shield.js:36:31)
    at Object.<anonymous> (app/src/permissions.js:52:21)
[ -- snipped node internals -- ]>
```

The actual error is inside my rule callback function, but I'd never know it from the stacktrace.

## To Reproduce

Steps to reproduce the behavior, please provide code snippets or a repository:

<details><summary>Example of how to replicate</summary>

1. This is my GraphQL Schema. 

```graphql
type Query {
  book: Book!
}

type Book {
  id: ID!
  name: String!
  content: String!
}
```

2. This is the invoked query

```graphql
book {
  id
  name
  content
}
```

3. I use these permissions

```ts
const { rule, shield } = require('graphql-shield');

const throw = rule()(() => {
  throw new Error('bad');
})

const permissions = shield({
  Query: {
    book: throw,
  }
})
```

4. The error is as the above stacktrace.

</details>

## Expected behavior

I would expect to see the full trace as to how and where the error occurred allowing me to debug fully.

## Additional context

I'm not sure what the benefits of caching the error object is (but I can imagine not generating the error most of the time will only increase performance, albeit a millisecond or two). If the error was generated upon encountering the issue (in the `try/catch`) then it'll give authors a clear idea of the problem.

I'd hope the change could be as straightforward as, instead of returning `options.fallbackError` in the catch, the `fallbackError` options property is a function that returns a new error - I'd imagine this could be done without a breaking change to the user facing API too (I'm a notice on TypeScript, but I might be able to create a PR if it would help).

**Comment by remy** [comment]
Hmm. I just found the `allowExternalErrors` and it gives me what I want for this particular case. Frustratingly my _real_ code still throws the internally generated error in graph-shield - so it's possible I'm hitting an actual bug in graph-shield and it's not in my code.

Annoying as I put a lot of detail in the original issue! :) 

Will close as there's a solution baked in!

Sorry for wasting anyone's time.
