### ISSUE TITLE
Upload Scalar with Apollo 2 midleware

### ISSUE THREAD

**Issue by Meghajnct** [maticzav/graphql-shield#324]
I am trying to use graphql-shield in my apollo-server2 . Which is built on top of express.
I was using makeExecutableSchema to apply applyMiddleware as suggested many places like : [https://gist.github.com/donedgardo/ed2d36f6e650991543e5a55c77cddc0d]
But getting error :' "Upload". Did you mean "Float"?'
This error is coming because I have 'Upload' scalar in my schema. And few post has suggested makeExecutableSchema and Upload scalar don't work together. :(

Do you have any other way to apply Middleware or graphql-shield  in apollo-server2

**Comment by maticzav** [comment]
hey @Meghajnct 👋,
Thanks for opening the issue. Could you also share the error log you are getting, schema and the server initiator function? This way I can help you better.

> PS.: a reproduction repo would be 💯💯

**Comment by Meghajnct** [comment]
imports ...

const app = express()

const schema = applyMiddleware(
  makeExecutableSchema({
    typeDefs:gqlOptions.typeDefs,
    resolvers: gqlOptions.resolvers
  }),
  permissions
);
const server = new ApolloServer({
  typeDefs: gqlOptions.typeDefs,
  resolvers: gqlOptions.resolvers,
  schema,
  context: async ({ req }) => {
      ....
     },
  formatError: (error, req) => {
    ...
  },
  persistedQueries: {
   ...
    )
  }
})

server.applyMiddleware({
  app: app
})

app.listen({ port: PORT }, () =>
  log.info(
    `Server ready at http://localhost:${PORT}`
    }
  )
)
`

And Error I am getting : 

../node_modules/graphql/validation/validate.js:89
    throw new Error(errors.map(function (error) {
    ^

Error: Unknown type "Upload". Did you mean "Float"?

Unknown type "Upload". Did you mean "Float"?

Unknown type "Upload". Did you mean "Float"?

Unknown type "Upload". Did you mean "Float"?

Unknown type "Upload". Did you mean "Float"?
    at assertValidSDL (/Users/meghagupta/dev/code/../node_modules/graphql/validation/validate.js:89:11)
    at Object.buildASTSchema (/Users/meghagupta/dev/code/../node_modules/graphql/utilities/buildASTSchema.js:78:34)
    at Object.buildSchemaFromTypeDefinitions (/Users/meghagupta/dev/code/.../node_modules/graphql-tools/src/generate/buildSchemaFromTypeDefinitions.ts:43:32)
    at makeExecutableSchema (/Users/meghagupta/dev/code/../node_modules/graphql-tools/src/makeExecutableSchema.ts:52:16)
    at Object.<anonymous> (/Users/meghagupta/dev/code/../src/server.js:38:3)
    at Module._compile (internal/modules/cjs/loader.js:689:30)
    at Module._compile (/Users/meghagupta/dev/code/../node_modules/pirates/lib/index.js:99:24)
    at Module._extensions..js (internal/modules/cjs/loader.js:700:10)
    at Object.newLoader [as .js] (/Users/meghagupta/dev/code/../node_modules/pirates/lib/index.js:104:7)
    at Module.load (internal/modules/cjs/loader.js:599:32)
    at tryModuleLoad (internal/modules/cjs/loader.js:538:12)
    at Function.Module._load (internal/modules/cjs/loader.js:530:3)
    at Function.Module.runMain (internal/modules/cjs/loader.js:742:12)
    at startup (internal/bootstrap/node.js:282:19)
    at bootstrapNodeJSCore (internal/bootstrap/node.js:743:3)

**Comment by maticzav** [comment]
and the schema 🙂

**Comment by P4sca1** [comment]
Afaik you should either provide `typeDefs` and `resolvers` **or** an already compiled `schema`.
So I would remove `typeDefs` and `resolvers` from your `apollo` constructor.
However I don't think this solves the issue. Instead something in your `gqlOptions.typeDefs` seems to be wrong.

**Comment by Meghajnct** [comment]
Yes, @P4sca1 you are correct. I have removed them still got same error. 
I think issue is I am using upload scalar, which is not go well with makeExecutableSchema.

**Comment by P4sca1** [comment]
Could you post your typeDefs?

**Comment by Meghajnct** [comment]
I have so many typeDefs. can't post all of then. but can post upload scalar one
its like : 
extend type Mutation {
addUsers(file: Upload!): UserResponseType
}

**Comment by P4sca1** [comment]
And where is the Upload type defined?

**Comment by Meghajnct** [comment]
its by apollo-graphql

**Comment by P4sca1** [comment]
I found something interesting in the docs:
> Apollo Server 2.0 automatically adds the Upload scalar to the schema, when you are not setting the schema manually.

So because you are setting the schema manually, apollo server does not automatically and the Upload scalar.

**Comment by P4sca1** [comment]
https://github.com/apollographql/apollo-server/issues/1317#issuecomment-403648624

**Comment by Meghajnct** [comment]
It does I am able to upload files

**Comment by Meghajnct** [comment]
They have fixed that issue.

**Comment by Meghajnct** [comment]
sry by mistake I click on close issue

**Comment by Meghajnct** [comment]
How I can open it again ? :(

**Comment by P4sca1** [comment]
> They have fixed that issue.

The error is not thrown by apollo-server but in the makeExecutableSchema call before.
This function has no clue about apollo-server adding the type later on so you can’t rely on it. You need to add the type manually to your typedefs.

**Comment by Meghajnct** [comment]
This issue is fixed. thanks a lot 👍

**Comment by duke7able** [comment]
I am having the same error, I tried many ways, one of which is asked on [https://spectrum.chat/graphql/general/best-strategies-to-implement-access-control-in-graphql~f497245c-ca95-471c-9263-209a584d30ff](spectrum), For the sake of simplicity I am just writing here for 1 api in query. I tried another way, that is :-
`let userPermissions = [];

const fetchPermissions = async token => {
  const user = await sequelize.models.User.findOne({
    where: { id: jwt.verify(token, process.env.JWT_SECRET).id }
  });
  const role = await sequelize.models.Role.findOne({
    where: { id: user.role_id }
  });
  const permissions = await role.getPermissions();
  userPermissions = permissions;
  console.log("user", user, role, permissions, isAdmin, isRoleActionTrue);
};

const isAdmin = rule()(async (parent, args, ctx, info) => {
  return true;
});

const isNotAdmin = rule()(async (parent, args, ctx, info) => {
  return false;
});

const isRoleActionTrue = rule()(async (parent, args, ctx, info) => {
  let returnValue = false;
  console.log("test", parent, args, ctx, info);
  userPermissions.forEach(({ name, isAction }) => {
    if (name === "ROLE" && isAction === true) {
      returnValue = true;
    }
  });
  return returnValue;
});

const resolvers = {
  Query: {
    getRole
  }
};

const permissions = shield({
  Query: {
    getRole: not(true)
  }
});

const schema = applyMiddleware(
  makeExecutableSchema({
    typeDefs,
    resolvers
  }),
  permisions
);

export default {
  typeDefs,
  resolvers,
  schema,
  context: ({ req }) => {
    console.log("here in context", shield);
    const token = req.headers.token || "";
    fetchPermissions(token);
    return {
      token,
      jwtEncode,
      jwtDecode,
      sequelize,
      passwordHash,
      comparePassword
    };
  }
};
`
the typeDef is :-
`  
  type Role {
    id: Int
    name: String
    status: Boolean
    permissions: [Permission]
  }

type Query {
    getRole: [Role]
  }`

error code is something like :- 
`    at Object.<anonymous> (/Users/shreyan.mehta/work/buyer-persona-Backend/buyer-persona-backend/index.js:14:1)
    at Module._compile (module.js:649:14)
    at Object.Module._extensions..js (module.js:663:10)
    at Module.load (module.js:565:32)
    at tryModuleLoad (module.js:505:12)
    at Function.Module._load (module.js:497:3)
    at Function.Module.runMain (module.js:693:10)
    at startup (bootstrap_node.js:188:16)
    at bootstrap_node.js:609:3`

**Comment by P4sca1** [comment]
https://github.com/maticzav/graphql-shield/issues/324#issuecomment-479810567

https://github.com/maticzav/graphql-shield/issues/324#issuecomment-479885730

Basically add scalar Upload to your typeDefs.

**Comment by P4sca1** [comment]
Maybe we should add this to the docs as it seems to be a common issue? @maticzav

**Comment by duke7able** [comment]
> [#324 (comment)](https://github.com/maticzav/graphql-shield/issues/324#issuecomment-479810567)
> 
> [#324 (comment)](https://github.com/maticzav/graphql-shield/issues/324#issuecomment-479885730)
> 
> Basically add scalar Upload to your typeDefs.

@P4sca1 thanks for the quick reply, I didnt actually knew that my colleague has this upload in api. I did added that, not getting that erro anymore, but I am getting a new error in rule , without even passing anything into it :- 
`TypeError: rule.extractFragment is not a function
    at fragments.rules.reduce (/Users/shreyan.mehta/work/buyer-persona-Backend/buyer-persona-backend/node_modules/graphql-shield/src/rules.ts:247:16)
    at Array.reduce (<anonymous>)
    at RuleNot.extractFragments (/Users/shreyan.mehta/work/buyer-persona-Backend/buyer-persona-backend/node_modules/graphql-shield/src/rules.ts:242:34)
    at generateFieldMiddlewareFromRule (/Users/shreyan.mehta/work/buyer-persona-Backend/buyer-persona-backend/node_modules/graphql-shield/src/generator.ts:86:23)
    at Object.keys.reduce (/Users/shreyan.mehta/work/buyer-persona-Backend/buyer-persona-backend/node_modules/graphql-shield/src/generator.ts:145:18)
    at Array.reduce (<anonymous>)
    at applyRuleToType (/Users/shreyan.mehta/work/buyer-persona-Backend/buyer-persona-backend/node_modules/graphql-shield/src/generator.ts:142:46)
    at Object.keys.filter.reduce (/Users/shreyan.mehta/work/buyer-persona-Backend/buyer-persona-backend/node_modules/graphql-shield/src/generator.ts:249:25)
    at Array.reduce (<anonymous>)
    at generateMiddlewareFromSchemaAndRuleTree (/Users/shreyan.mehta/work/buyer-persona-Backend/buyer-persona-backend/node_modules/graphql-shield/src/generator.ts:243:8)
    at MiddlewareGenerator.generator (/Users/shreyan.mehta/work/buyer-persona-Backend/buyer-persona-backend/node_modules/graphql-shield/src/generator.ts:277:24)
    at MiddlewareGenerator.generate (/Users/shreyan.mehta/work/buyer-persona-Backend/buyer-persona-backend/node_modules/graphql-middleware/src/generator.ts:19:17)
    at /Users/shreyan.mehta/work/buyer-persona-Backend/buyer-persona-backend/node_modules/graphql-middleware/src/middleware.ts:72:25
    at Array.map (<anonymous>)
    at applyMiddlewareWithOptions (/Users/shreyan.mehta/work/buyer-persona-Backend/buyer-persona-backend/node_modules/graphql-middleware/src/middleware.ts:70:45)
    at applyMiddleware (/Users/shreyan.mehta/work/buyer-persona-Backend/buyer-persona-backend/node_modules/graphql-middleware/src/middleware.ts:129:36)
    at Object.<anonymous> (/Users/shreyan.mehta/work/buyer-persona-Backend/buyer-persona-backend/graphql/index.js:179:16)
    at Module._compile (module.js:652:30)
    at loader (/Users/shreyan.mehta/work/buyer-persona-Backend/buyer-persona-backend/node_modules/babel-register/lib/node.js:144:5)
    at Object.require.extensions.(anonymous function) [as .js] (/Users/shreyan.mehta/work/buyer-persona-Backend/buyer-persona-backend/node_modules/babel-register/lib/node.js:154:7)
    at Module.load (module.js:565:32)
    at tryModuleLoad (module.js:505:12)
    at Function.Module._load (module.js:497:3)
    at Module.require (module.js:596:17)
    at require (internal/module.js:11:18)
    at Object.<anonymous> (/Users/shreyan.mehta/work/buyer-persona-Backend/buyer-persona-backend/server.js:3:1)
    at Module._compile (module.js:652:30)
    at loader (/Users/shreyan.mehta/work/buyer-persona-Backend/buyer-persona-backend/node_modules/babel-register/lib/node.js:144:5)
    at Object.require.extensions.(anonymous function) [as .js] (/Users/shreyan.mehta/work/buyer-persona-Backend/buyer-persona-backend/node_modules/babel-register/lib/node.js:154:7)
    at Module.load (module.js:565:32)
    at tryModuleLoad (module.js:505:12)
    at Function.Module._load (module.js:497:3)
    at Module.require (module.js:596:17)
    at require (internal/module.js:11:18)`

**Comment by P4sca1** [comment]
The problem lies in your permissions.
You cant do not(true). The logical rules and and or only work with other rules. So you need to use not(allow) or deny. Those are default rules which can be imported from graphql-shield.
