### ISSUE TITLE
Upgrading from 5.6.2 to 5.7.0 causes promise bug

### ISSUE THREAD

**Issue by Victordmdb** [maticzav/graphql-shield#404]
When upgrading from 5.6.2 to 5.7.0, with no other changes in the codebase I get the error below when making a query through graphql playground. 

The field and query can be replaced with any other, the error is the same.

```ts
{
  "errors": [
    {
      "message": "Unknown object type \"promise\"",
      "locations": [
        {
          "line": 9,
          "column": 3
        }
      ],
      "path": [
        "account",
        "name"
      ],
      "extensions": {
        "code": "INTERNAL_SERVER_ERROR",
        "exception": {
          "stacktrace": [
            "Error: Unknown object type \"promise\"",
            "    at Object._object (PATH/node_modules/object-hash/index.js:218:17)",
            "    at Object.dispatch (PATH/node_modules/object-hash/index.js:185:30)",
            "    at PATH/node_modules/object-hash/index.js:246:18",
            "    at Array.forEach (<anonymous>)",
            "    at Object._object (PATH/node_modules/object-hash/index.js:242:21)",
            "    at Object._function (PATH/node_modules/object-hash/index.js:319:14)",
            "    at Object.dispatch (PATH/node_modules/object-hash/index.js:185:30)",
            "    at PATH/node_modules/object-hash/index.js:246:18",
            "    at Array.forEach (<anonymous>)",
            "    at Object._object (PATH/node_modules/object-hash/index.js:242:21)",
            "    at Object.dispatch (PATH/node_modules/object-hash/index.js:185:30)",
            "    at PATH/node_modules/object-hash/index.js:246:18",
            "    at Array.forEach (<anonymous>)",
            "    at Object._object (PATH/node_modules/object-hash/index.js:242:21)",
            "    at Object.dispatch (PATH/node_modules/object-hash/index.js:185:30)",
            "    at PATH/node_modules/object-hash/index.js:246:18",
            "    at Array.forEach (<anonymous>)",
            "    at Object._object (PATH/node_modules/object-hash/index.js:242:21)",
            "    at Object.dispatch (PATH/node_modules/object-hash/index.js:185:30)",
            "    at hash (PATH/node_modules/object-hash/index.js:128:10)",
            "    at Object.objectHash [as hashFunction] (PATH/node_modules/object-hash/index.js:33:10)",
            "    at Rule.generateCacheKey (PATH/node_modules/graphql-shield/src/rules.ts:156:33)",
            "    at Rule.<anonymous> (PATH/node_modules/graphql-shield/src/rules.ts:53:29)",
            "    at Generator.next (<anonymous>)",
            "    at PATH/node_modules/graphql-shield/dist/rules.js:7:71",
            "    at new Promise (<anonymous>)",
            "    at __awaiter (PATH/node_modules/graphql-shield/dist/rules.js:3:12)",
            "    at Rule.resolve (PATH/node_modules/graphql-shield/dist/rules.js:31:16)"
          ]
        }
      }
    },
    {
      "message": "Unknown object type \"promise\"",
      "locations": [
        {
          "line": 11,
          "column": 3
        }
      ],
      "path": [
        "account",
        "createdAt"
      ],
      "extensions": {
        "code": "INTERNAL_SERVER_ERROR",
        "exception": {
          "stacktrace": [
            "Error: Unknown object type \"promise\"",
            "    at Object._object (PATH/node_modules/object-hash/index.js:218:17)",
            "    at Object.dispatch (PATH/node_modules/object-hash/index.js:185:30)",
            "    at PATH/node_modules/object-hash/index.js:246:18",
            "    at Array.forEach (<anonymous>)",
            "    at Object._object (PATH/node_modules/object-hash/index.js:242:21)",
            "    at Object._function (PATH/node_modules/object-hash/index.js:319:14)",
            "    at Object.dispatch (PATH/node_modules/object-hash/index.js:185:30)",
            "    at PATH/node_modules/object-hash/index.js:246:18",
            "    at Array.forEach (<anonymous>)",
            "    at Object._object (PATH/node_modules/object-hash/index.js:242:21)",
            "    at Object.dispatch (PATH/node_modules/object-hash/index.js:185:30)",
            "    at PATH/node_modules/object-hash/index.js:246:18",
            "    at Array.forEach (<anonymous>)",
            "    at Object._object (PATH/node_modules/object-hash/index.js:242:21)",
            "    at Object.dispatch (PATH/node_modules/object-hash/index.js:185:30)",
            "    at PATH/node_modules/object-hash/index.js:246:18",
            "    at Array.forEach (<anonymous>)",
            "    at Object._object (PATH/node_modules/object-hash/index.js:242:21)",
            "    at Object.dispatch (PATH/node_modules/object-hash/index.js:185:30)",
            "    at hash (PATH/node_modules/object-hash/index.js:128:10)",
            "    at Object.objectHash [as hashFunction] (PATH/node_modules/object-hash/index.js:33:10)",
            "    at Rule.generateCacheKey (PATH/node_modules/graphql-shield/src/rules.ts:156:33)",
            "    at Rule.<anonymous> (PATH/node_modules/graphql-shield/src/rules.ts:53:29)",
            "    at Generator.next (<anonymous>)",
            "    at PATH/node_modules/graphql-shield/dist/rules.js:7:71",
            "    at new Promise (<anonymous>)",
            "    at __awaiter (PATH/node_modules/graphql-shield/dist/rules.js:3:12)",
            "    at Rule.resolve (PATH/node_modules/graphql-shield/dist/rules.js:31:16)"
          ]
        }
      }
    },
    {
      "message": "Unknown object type \"promise\"",
      "locations": [
        {
          "line": 13,
          "column": 3
        }
      ],
      "path": [
        "account",
        "organisation"
      ],
      "extensions": {
        "code": "INTERNAL_SERVER_ERROR",
        "exception": {
          "stacktrace": [
            "Error: Unknown object type \"promise\"",
            "    at Object._object (PATH/node_modules/object-hash/index.js:218:17)",
            "    at Object.dispatch (PATH/node_modules/object-hash/index.js:185:30)",
            "    at PATH/node_modules/object-hash/index.js:246:18",
            "    at Array.forEach (<anonymous>)",
            "    at Object._object (PATH/node_modules/object-hash/index.js:242:21)",
            "    at Object._function (PATH/node_modules/object-hash/index.js:319:14)",
            "    at Object.dispatch (PATH/node_modules/object-hash/index.js:185:30)",
            "    at PATH/node_modules/object-hash/index.js:246:18",
            "    at Array.forEach (<anonymous>)",
            "    at Object._object (PATH/node_modules/object-hash/index.js:242:21)",
            "    at Object.dispatch (PATH/node_modules/object-hash/index.js:185:30)",
            "    at PATH/node_modules/object-hash/index.js:246:18",
            "    at Array.forEach (<anonymous>)",
            "    at Object._object (PATH/node_modules/object-hash/index.js:242:21)",
            "    at Object.dispatch (PATH/node_modules/object-hash/index.js:185:30)",
            "    at PATH/node_modules/object-hash/index.js:246:18",
            "    at Array.forEach (<anonymous>)",
            "    at Object._object (PATH/node_modules/object-hash/index.js:242:21)",
            "    at Object.dispatch (PATH/node_modules/object-hash/index.js:185:30)",
            "    at hash (PATH/node_modules/object-hash/index.js:128:10)",
            "    at Object.objectHash [as hashFunction] (PATH/node_modules/object-hash/index.js:33:10)",
            "    at Rule.generateCacheKey (PATH/node_modules/graphql-shield/src/rules.ts:156:33)",
            "    at Rule.<anonymous> (PATH/node_modules/graphql-shield/src/rules.ts:53:29)",
            "    at Generator.next (<anonymous>)",
            "    at PATH/node_modules/graphql-shield/dist/rules.js:7:71",
            "    at new Promise (<anonymous>)",
            "    at __awaiter (PATH/node_modules/graphql-shield/dist/rules.js:3:12)",
            "    at Rule.resolve (PATH/node_modules/graphql-shield/dist/rules.js:31:16)"
          ]
        }
      }
    },
    {
      "message": "Unknown object type \"promise\"",
      "locations": [
        {
          "line": 8,
          "column": 3
        }
      ],
      "path": [
        "account",
        "_id"
      ],
      "extensions": {
        "code": "INTERNAL_SERVER_ERROR",
        "exception": {
          "stacktrace": [
            "Error: Unknown object type \"promise\"",
            "    at Object._object (PATH/node_modules/object-hash/index.js:218:17)",
            "    at Object.dispatch (PATH/node_modules/object-hash/index.js:185:30)",
            "    at PATH/node_modules/object-hash/index.js:246:18",
            "    at Array.forEach (<anonymous>)",
            "    at Object._object (PATH/node_modules/object-hash/index.js:242:21)",
            "    at Object._function (PATH/node_modules/object-hash/index.js:319:14)",
            "    at Object.dispatch (PATH/node_modules/object-hash/index.js:185:30)",
            "    at PATH/node_modules/object-hash/index.js:246:18",
            "    at Array.forEach (<anonymous>)",
            "    at Object._object (PATH/node_modules/object-hash/index.js:242:21)",
            "    at Object.dispatch (PATH/node_modules/object-hash/index.js:185:30)",
            "    at PATH/node_modules/object-hash/index.js:246:18",
            "    at Array.forEach (<anonymous>)",
            "    at Object._object (PATH/node_modules/object-hash/index.js:242:21)",
            "    at Object.dispatch (PATH/node_modules/object-hash/index.js:185:30)",
            "    at PATH/node_modules/object-hash/index.js:246:18",
            "    at Array.forEach (<anonymous>)",
            "    at Object._object (PATH/node_modules/object-hash/index.js:242:21)",
            "    at Object.dispatch (PATH/node_modules/object-hash/index.js:185:30)",
            "    at hash (PATH/node_modules/object-hash/index.js:128:10)",
            "    at Object.objectHash [as hashFunction] (PATH/node_modules/object-hash/index.js:33:10)",
            "    at Rule.generateCacheKey (PATH/node_modules/graphql-shield/src/rules.ts:156:33)",
            "    at Rule.<anonymous> (PATH/node_modules/graphql-shield/src/rules.ts:53:29)",
            "    at Generator.next (<anonymous>)",
            "    at PATH/node_modules/graphql-shield/dist/rules.js:7:71",
            "    at new Promise (<anonymous>)",
            "    at __awaiter (PATH/node_modules/graphql-shield/dist/rules.js:3:12)",
            "    at Rule.resolve (PATH/node_modules/graphql-shield/dist/rules.js:31:16)"
          ]
        }
      }
    }
  ],
  "data": {
    "account": null
  }
}
```

**Comment by maticzav** [comment]
@Victordmdb thank you for reporting this. Could you try upgrading GraphQL Shield to the latest version and verify that this issue is still relevant? A reproduction repository would be great.

**Comment by aboe026** [comment]
I'm also seeing this in my own project after upgrading to
```
"graphql-shield": "6.0.3"
```
from
```
"graphql-shield": "5.3.5"
```

**Comment by aboe026** [comment]
also, here is my stacktrace:
```
{
   "errors":[
      {
         "message":"Unknown object type \"promise\"",
         "locations":[
            {
               "line":2,
               "column":3
            }
         ],
         "path":[
            "addPhoto"
         ],
         "extensions":{
            "code":"INTERNAL_SERVER_ERROR",
            "exception":{
               "stacktrace":[
                  "Error: Unknown object type \"promise\"",
                  "    at Object._object (PATH\\node_modules\\object-hash\\index.js:218:17)",
                  "    at Object.dispatch (PATH\\node_modules\\object-hash\\index.js:185:30)",
                  "    at PATH\\node_modules\\object-hash\\index.js:246:18",
                  "    at Array.forEach (<anonymous>)",
                  "    at Object._object (PATH\\node_modules\\object-hash\\index.js:242:21)",
                  "    at Object.dispatch (PATH\\node_modules\\object-hash\\index.js:185:30)",
                  "    at PATH\\node_modules\\object-hash\\index.js:246:18",
                  "    at Array.forEach (<anonymous>)",
                  "    at Object._object (PATH\\node_modules\\object-hash\\index.js:242:21)",
                  "    at Object.dispatch (PATH\\node_modules\\object-hash\\index.js:185:30)",
                  "    at hash (PATH\\node_modules\\object-hash\\index.js:128:10)",
                  "    at Object.objectHash [as hashFunction] (PATH\\node_modules\\object-hash\\index.js:33:10)",
                  "    at Rule.generateCacheKey (PATH\\node_modules\\graphql-shield\\src\\rules.ts:156:33)",
                  "    at Rule.resolve (PATH\\node_modules\\graphql-shield\\src\\rules.ts:53:29)",
                  "    at rules.map.rule (PATH\\node_modules\\graphql-shield\\src\\rules.ts:228:12)",
                  "    at Array.map (<anonymous>)",
                  "    at RuleAnd.evaluate (PATH\\node_modules\\graphql-shield\\src\\rules.ts:227:25)",
                  "    at RuleAnd.resolve (PATH\\node_modules\\graphql-shield\\src\\rules.ts:317:31)",
                  "    at middleware (PATH\\node_modules\\graphql-shield\\src\\generator.ts:62:30)",
                  "    at PATH\\node_modules\\graphql-middleware\\src\\applicator.ts:32:5",
                  "    at field.resolve (PATH\\node_modules\\apollo-server-express\\node_modules\\graphql-extensions\\src\\index.ts:277:18)",
                  "    at resolveFieldValueOrError (PATH\\node_modules\\graphql\\execution\\execute.js:503:18)",
                  "    at resolveField (PATH\\node_modules\\graphql\\execution\\execute.js:470:16)",
                  "    at PATH\\node_modules\\graphql\\execution\\execute.js:280:18",
                  "    at PATH\\node_modules\\graphql\\jsutils\\promiseReduce.js:23:10",
                  "    at Array.reduce (<anonymous>)",
                  "    at promiseReduce (PATH\\node_modules\\graphql\\jsutils\\promiseReduce.js:20:17)",
                  "    at executeFieldsSerially (PATH\\node_modules\\graphql\\execution\\execute.js:277:37)"
               ]
            }
         }
      }
   ],
   "data":{
      "addPhoto":null
   }
}
```

**Comment by maticzav** [comment]
I see! Could you create a reproduction repository? This way, I can fix the issue more quickly.

**Comment by smschick** [comment]
I also have the same outcome/error messages for unknown object type.  Just downgraded from "5.7.3" to "5.6.2" and it works as expected.   While doing some digging I noticed that if I hard coded the "ignoreUnknown" option to true in the object-hash module 5.7.2 would work as well.   The object type it wasn't recognizing/liking for my project was a "promise" coming from a file upload scalar (graphql-upload)

**Comment by maticzav** [comment]
`5.7.0` introduced a new default caching option. Due to `strict` evaluation which relied on `hash`, as mentioned, the bug appeared.

The latest version (`6.0.6`) fixed that by changing the default cache option to `no_cache`.

Thank you all for providing beneficial information. Please let me know if anyone still experiences the problem.
