### ISSUE TITLE
Shield rules with cache: "strict" don't work on types.

### ISSUE THREAD

**Issue by raaymax** [maticzav/graphql-shield#487]
# Bug report

* [x ] I have checked other issues to make sure this is not a duplicate.

## Describe the bug

When using shield rule on type with `cache: "strict"` authorization result is always "Not Authorized"  

## To Reproduce

Steps to reproduce the behavior, please provide code snippets or a repository:

> (Delete the filler code and replace it with your own)

1. This is my GraphQL Schema. 

```graphql
type Query {
  clinics: [Clinic]!
}

type Clinic {
  id: ID!
  name: String!
}
```

2. This is the invoked query

```graphql
clinics {
  id
  name
}
```

3. I use these permissions

```ts
const permissions = shield({
  Query: {
    clinics: allow,
  },
  Clinic: rule({ cache: 'strict' })(async (parent, args, ctx, info) => {
    return true;
  }),,
})
```

4. All results are not authorized. 

## Expected behavior
Rule should be called once per "Type" and validate access to it.

## Actual behaviour
Rule always return "Not authorized"

## Additional 

If this is wrong usage of rules then it should be somehow thrown as an error

**Comment by maticzav** [comment]
@raaymax thank you for opening the issue. Could you provide a small reproduction repository? This way, I can help you with the bug a lot more quickly. 🙂

**Comment by todda00** [comment]
I have run into this issue, but specifically only when a parent is null and cache === "strict". The rule does not even run at all. When debug=true, the following error is output:

```
Cannot read property '3' of undefined
```
stacktrace:
```
TypeError: Cannot read property '3' of undefined,
    at Object.get [as generationTime] ([redacted]/node_modules/bson/lib/bson/objectid.js:373:19),
    at [redacted]/node_modules/object-hash/index.js:246:33,
    at Array.forEach (<anonymous>),
    at Object._object ([redacted]/node_modules/object-hash/index.js:242:21),
    at Object.dispatch ([redacted]/node_modules/object-hash/index.js:185:30),
    at [redacted]/node_modules/object-hash/index.js:246:18,
    at Array.forEach (<anonymous>),
    at Object._object ([redacted]/node_modules/object-hash/index.js:242:21),
    at Object.dispatch ([redacted]/node_modules/object-hash/index.js:185:30),
    at [redacted]/node_modules/object-hash/index.js:246:18,
    at Array.forEach (<anonymous>),
    at Object._object ([redacted]/node_modules/object-hash/index.js:242:21),
    at Object.dispatch ([redacted]/node_modules/object-hash/index.js:185:30),
    at [redacted]/node_modules/object-hash/index.js:246:18,
    at Array.forEach (<anonymous>),
    at Object._object ([redacted]/node_modules/object-hash/index.js:242:21),
    at Object.dispatch ([redacted]/node_modules/object-hash/index.js:185:30),
    at hash ([redacted]/node_modules/object-hash/index.js:128:10),
    at Object.objectHash [as hashFunction] ([redacted]/node_modules/object-hash/index.js:33:10),
    at Rule.executeRule ([redacted]/node_modules/graphql-shield/src/rules.ts:162:33),
    at Rule.resolve ([redacted]/node_modules/graphql-shield/src/rules.ts:58:30),
    at middleware ([redacted]/node_modules/graphql-shield/src/generator.ts:67:30),
    at [redacted]/node_modules/graphql-middleware/src/applicator.ts:32:5,
    at field.resolve ([redacted]/node_modules/apollo-server-core/node_modules/graphql-extensions/src/index.ts:274:18),
    at resolveFieldValueOrError ([redacted]/node_modules/graphql/execution/execute.js:503:18),
    at resolveField ([redacted]/node_modules/graphql/execution/execute.js:470:16),
    at executeFields ([redacted]/node_modules/graphql/execution/execute.js:311:18),
    at collectAndExecuteSubfields ([redacted]/node_modules/graphql/execution/execute.js:747:10),
    at completeObjectValue ([redacted]/node_modules/graphql/execution/execute.js:737:10),
    at completeValue ([redacted]/node_modules/graphql/execution/execute.js:626:12),
    at [redacted]/node_modules/graphql/execution/execute.js:528:16,
    at process._tickCallback (internal/process/next_tick.js:68:7)

```

**Comment by maticzav** [comment]
I cannot help much without a reproduction.

**Comment by maticzav** [comment]
I tried reproducing this bug but had no luck. You can see what I did in the sandbox I provided below. Feel free to reopen the issue if I did something wrong in my reproduction.

https://codesandbox.io/s/graphql-shield-issue-487-irsn5

**Comment by todda00** [comment]
I can't seem to recreate this issue anymore either - I have set all my rules back from no_cache to strict which were strict previously. As we test the app I will let you know if anything pops up, but I can't recreate it inside our app, or in the sandbox you provided.

**Comment by todda00** [comment]
ah ha! I figured out the rhyme and reason this error is popping up. We use MongoDB and for most of our data the _id field is a string, but for some historical data it uses's Mongo's ObjectID, which when it comes across graphql gets converted to a string, but when a strict rule from graphql-shield is involved, it fails to read the parent data correctly and doesn't even run the rule. Here is the sandbox with a reproduction:

https://codesandbox.io/s/graphql-shield-issue-487-19bl0

Obviously I would understand if you don't want to handle ObjectIDs as ids within graphql-shield, we are going to covert all historical data to use strings so this issue won't be one anymore for us, but I wanted to share my findings because I am sure someone else will try using graphql-shield with Mongo's ObjectIDs and run into this.
