### ISSUE TITLE
`generated/nexus-prisma` folder not being generated

### ISSUE THREAD

**Issue by alnimra** [maticzav/graphql-shield#600]
# Bug report

## Describe the bug

When running the example `with-graphql-nexus` there are a few problems:
1. The `datamodel.prisma` seems to be out of date
    - `@id` modifier should be on the User's id tag
    - `@createdAt` and `@updatedAt` should be added as well
2. The `docker-compose.yml` has to have the version updated with the current prisma cli as well
3. When we run `prisma deploy` it doesn't generate the `./src/generated/nexus-prisma` directory. Which gives an error for the module not being found when running `yarn start`

## To Reproduce

Steps to reproduce the behavior, please provide code snippets or a repository:
1. The deployment steps in the README of `with-graphql-nexus` along with the fixes 1 and 2 above.
2. On the step with `yarn start` I get the error below, which I found is because the `./src/generated/nexus-prisma` directory isn't generated with `prisma deploy`
```ts
Error: Cannot find module '../generated/nexus-prisma'
    at Function.Module._resolveFilename (internal/modules/cjs/loader.js:636:15)
    at Function.Module._load (internal/modules/cjs/loader.js:562:25)
    at Module.require (internal/modules/cjs/loader.js:692:17)
    at require (internal/modules/cjs/helpers.js:25:18)
    at Object.<anonymous> (/Users/alnim/Downloads/graphql-shield/examples/with-graphql-nexus/src/schema/index.js:4:23)
    at Module._compile (internal/modules/cjs/loader.js:778:30)
    at Object.Module._extensions..js (internal/modules/cjs/loader.js:789:10)
    at Module.load (internal/modules/cjs/loader.js:653:32)
    at tryModuleLoad (internal/modules/cjs/loader.js:593:12)
    at Function.Module._load (internal/modules/cjs/loader.js:585:3)
```

## Expected behavior

`yarn start` should start the node server, with no errors. `prisma deploy` should generate the `nexus-prisma` directory.

**Comment by maticzav** [comment]
@alnimra thank you for opening this issue. You can find a working version in the link below.

https://github.com/prisma/prisma-examples/tree/prisma2/typescript/graphql-auth
